# Generated by Django 5.0.1 on 2024-01-20 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='入会日'),
        ),
    ]
